# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
            },
        ),
        migrations.RemoveField(
            model_name='itemmeal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='itemmeal',
            name='value',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_meal',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_date',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='quantity_people',
        ),
        migrations.AddField(
            model_name='itemmeal',
            name='properties',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Propriedades'),
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default='2017-01-01', verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='plate',
            field=models.ManyToManyField(related_name='plate_meal', to='meal.Plate', verbose_name='Prato'),
        ),
        migrations.AddField(
            model_name='plate',
            name='name',
            field=models.CharField(default='Plate', max_length=100, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmeal',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='end_time',
            field=models.TimeField(verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='start_time',
            field=models.TimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='item_meal',
            field=models.ManyToManyField(related_name='item_plate', to='meal.ItemMeal', verbose_name='Itens da Refeição'),
        ),
        migrations.AddField(
            model_name='itemmeal',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='allergy_item', to='meal.Allergy', verbose_name='Alergias'),
        ),
    ]
