# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-31 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20161222_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='item_meal',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='plate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meal.Plate', verbose_name='Prato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmeal',
            name='properties',
            field=models.CharField(default='', max_length=100, verbose_name='Propriedades'),
        ),
    ]
