# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-31 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_auto_20161231_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='name',
            field=models.CharField(default='Prato', max_length=100, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
