# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_auto_20161231_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Alergias',
                'verbose_name': 'Alergia',
            },
        ),
        migrations.AlterField(
            model_name='meal',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_meal', to='meal.Plate', verbose_name='Prato'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='item_meal',
            field=models.ManyToManyField(related_name='items', to='meal.ItemMeal', verbose_name='Itens da Refeição'),
        ),
        migrations.AddField(
            model_name='itemmeal',
            name='allergy',
            field=models.ManyToManyField(related_name='allergy_item', to='meal.Allergy', verbose_name='Alergias'),
        ),
    ]
