# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_auto_20170101_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.AlterField(
            model_name='itemmeal',
            name='properties',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Propriedades'),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='plate',
        ),
        migrations.AddField(
            model_name='meal',
            name='plate',
            field=models.ManyToManyField(related_name='plate_meal', to='meal.Plate', verbose_name='Prato'),
        ),
    ]
