# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_auto_20170102_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmeal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='itemmeal',
            name='value',
        ),
    ]
