# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_auto_20170102_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmeal',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='allergy_item', to='meal.Allergy', verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='item_meal',
            field=models.ManyToManyField(related_name='item_plate', to='meal.ItemMeal', verbose_name='Itens da Refeição'),
        ),
    ]
