# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_auto_20170102_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='end_time',
            field=models.TimeField(verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='start_time',
            field=models.TimeField(verbose_name='Início'),
        ),
    ]
