# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 02:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('meal', '0002_auto_20170106_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_check', to='meal.Meal', verbose_name='Refeição')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_check', to='meal.Plate', verbose_name='Prato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('registration', models.CharField(default='', max_length=255, verbose_name='Matrícula')),
                ('cpf', models.CharField(default='', max_length=255, verbose_name='CPF')),
                ('rg', models.CharField(default='', max_length=255, verbose_name='RG')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apelido')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='', max_length=1, verbose_name='Gênero')),
                ('father_name', models.CharField(default='', max_length=255, verbose_name='Nome do Pai')),
                ('father_occupation', models.CharField(default='', max_length=255, verbose_name='Profissão do Pai')),
                ('mother_name', models.CharField(default='', max_length=255, verbose_name='Nome da Mãe')),
                ('mother_occupation', models.CharField(default='', max_length=255, verbose_name='Profissão da Mãe')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Telefone')),
                ('birth', models.DateField(verbose_name='Data de Nascimento')),
                ('postal_code', models.CharField(default='', max_length=9, verbose_name='CEP')),
                ('city', models.CharField(default='', max_length=255, verbose_name='Cidade')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(default='', max_length=255, verbose_name='Número')),
                ('district', models.CharField(default='', max_length=255, verbose_name='Bairro')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cadastro-aluno/', verbose_name='Foto')),
                ('allergy', models.ManyToManyField(blank=True, related_name='allergy_student', to='meal.Allergy', verbose_name='Alergias')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['-created_on'],
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_check', to='student.Student', verbose_name='Aluno'),
        ),
    ]
