# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('num_matricula', models.CharField(max_length=255, null=True, verbose_name='Numero da Matricula')),
                ('cpf', models.CharField(max_length=255, null=True)),
                ('rg', models.CharField(max_length=255, null=True)),
                ('apelido', models.CharField(max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('nome_pai', models.CharField(max_length=255, null=True, verbose_name='Nome do Pai')),
                ('prof_pai', models.CharField(max_length=255, null=True, verbose_name='Profissão')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('prof_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para contato')),
                ('datanascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero')),
                ('complemento', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(null=True, upload_to='cadastro-aluno/')),
                ('texto', models.TextField(null=True, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['created_on'],
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
