# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_auto_20170101_1926'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='student',
            name='datacadastro',
        ),
        migrations.RemoveField(
            model_name='student',
            name='datanascimento',
        ),
        migrations.RemoveField(
            model_name='student',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='student',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nome_pai',
        ),
        migrations.RemoveField(
            model_name='student',
            name='num',
        ),
        migrations.RemoveField(
            model_name='student',
            name='num_matricula',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prof_mae',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prof_pai',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='texto',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_number',
            field=models.CharField(default='', max_length=255, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy',
            field=models.ManyToManyField(related_name='allergy_student', to='meal.Allergy', verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(default='', max_length=255, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(default='', max_length=255, verbose_name='Profissão do Pai'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='', max_length=1, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(default='', max_length=255, verbose_name='Profissão da Mãe'),
        ),
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(default='', max_length=255, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cadastro-aluno/'),
        ),
        migrations.AddField(
            model_name='student',
            name='postal_code',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='student',
            name='reference',
            field=models.CharField(default='', max_length=255, verbose_name='Referência'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.CharField(default='', max_length=255, verbose_name='Número de Matricula'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(default='', max_length=255, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(default='', max_length=255, verbose_name='RG'),
        ),
    ]
