# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_auto_20170102_2202'),
        ('student', '0003_auto_20170101_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_check', to='meal.Meal', verbose_name='Refeição')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_check', to='meal.Plate', verbose_name='Prato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_on'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AddField(
            model_name='check',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_check', to='student.Student', verbose_name='Aluno'),
        ),
    ]
