# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20170102_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='allergy_student', to='meal.Allergy', verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cadastro-aluno/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(default='', max_length=255, verbose_name='Matrícula'),
        ),
    ]
